### ISSUE TITLE
requests.exceptions.HTTPError: Invalid input from client.get_block

### ISSUE THREAD

**Issue by williamium3000** [jamalex/notion-py#382] opened 2023-01-06 16:28 UTC
I get the requests.exceptions.HTTPError: Invalid problem when calling client.get_block()
I don't get a solution from previous issues. What do you think is the best practice now or how can I fix this?

```
from notion.client import NotionClient
from notion.block import PageBlock
client = NotionClient(token_v2="xxx")
page = client.get_block("https://www.notion.so/xxx-xxx")
```

**Comment by yffenim** [comment] 2023-01-14 11:23
I am getting the exacty same issue. All I did was replace the values for token_v2 and the page url with my own exactly as shown in readme. 

```python
from notion.client import NotionClient

notion_token_from_header = 'str'
notion_page = 'https://www.notion.so/___/___'

client = NotionClient(token_v2=notion_token_from_header)
print(client) # this part is working

page = client.get_block(notion_page) # this gives error
```

**Comment by tyePhDCandy** [comment] 2023-01-29 06:03
I am getting the exact same issue. All I did was replace the values for token_v2 and the page url with my own exactly as shown in readme.
I highly doubt that it's a proxy problem, since we all come from mainland, china. This issue can not be solved by using vpn, it can only be solved by setting proxy server into parameters of certain functions.

**Comment by bishalnepali** [comment] 2023-02-01 20:58
Also getting the same issues :(

**Comment by egeres** [comment] 2023-02-06 22:31
Is it possible this issue is fixed in this fork? https://github.com/vzhd1701/notion-py

**Comment by mhsong55** [comment] 2023-02-07 02:20
I had the same issue and solved it.
The cause was in the cookie value (token_v2).
I cleared the cookie value in the web browser and refreshed the browser.
After that, I proceeded based on the newly received cookie value, and it worked normally.

**Comment by tyePhDCandy** [comment] 2023-02-07 07:12
I have already switched to [notion-sdk-py](https://github.com/ramnes/notion-sdk-py) and [notional](https://github.com/jheddings/notional). They are both very active repositories.

**Comment by williamium3000** [comment] 2023-02-09 20:24
vpn is not the issue, I am currently US still not working

**Comment by williamium3000** [comment] 2023-02-09 21:12
Hi all,
the issue is solved by https://github.com/vzhd1701/notion-py as stated by @mhsong55. Thanks
The problem is that the 0.36.0 is not updated to pip, thus directly using pip cannot install the newest version.
My approach is download from github the source code from https://github.com/vzhd1701/notion-py
and install through
`pip install .`

**Closed** 2023-02-11 22:24 UTC
