### ISSUE TITLE
Reminder functionality not present in pypi release

### ISSUE THREAD

**Issue by KShivendu** [jamalex/notion-py#208] opened 2020-10-29 05:30 UTC
I just saw that reminder functionality isn't present in the pypi release of the library. Please fix it.

**Comment by AlJohri** [comment] 2020-11-12 16:25
dupe of https://github.com/jamalex/notion-py/issues/196

**Comment by jamalex** [comment] 2020-11-22 06:03
Will be releasing tonight -- thanks for the bumps!

**Closed by jamalex** 2020-11-22 06:03 UTC
