### ISSUE TITLE
De-activable Markdown conversion in CodeBlock

### ISSUE THREAD

**Issue by aureliensibiril** [jamalex/notion-py#31] opened 2019-05-23 14:08 UTC
While using markdown_to_notion() for the ```title``` property makes lot's of sense for most blocks, it might be an issue for ```CodeBlock```.

I saw that property_map has a flag for markdown conversion but it's not accessible from the block initialisation. 

https://github.com/jamalex/notion-py/blob/ef0c5e02bd4ae5ad8d34c6c56e4e842b15aeaa01/notion/maps.py#L47

**Comment by Cobertos** [comment] 2019-12-17 00:08
I'm having issues with this while trying to upload yaml documents of the format

```yaml
title: Test
tags:
  - Video Game Art
  - Blender
  - Modelling
  - Render
  - Cycles
  - Quackventures
permalink: test
id: 59f834a1fe4ed100192567da
updated: '2018-06-14T07:20:33.000Z'
date: 2016-02-08 03:59:20
```

cause issues. The yaml array gets parsed as Markdown and each line becomes separated by a new line and loses the array prefix `  - `

**Comment by Cobertos** [comment] 2019-12-17 00:48
After further investigation, you can monkey-patch `markdown=False` with 

```python
from notion.block import CodeBlock
from notion.maps import property_map
CodeBlock.title = property_map('title', markdown=False)
```

but the problem is the `CodeBlock` actually supports Markdown in it (?!). So you'll get `CodeBlock`'s from the backend looking like

```python
[['titl'], ['e: Bobskater mmmmA Pytho', [['b']]], ['n obfuscation Library\ntags:\nmmmm'], ['Python\nmmmmpython3\nmmmmbobskater\nmmmmobfuscatio', [['s']]], ['n\nmmm'], ['mminify\nmmmmast\nmmmmabs', [['h', 'red']]], ["tract syntax tree\nmmmmregex\npermalink: bobskater-a-python-obfuscation-library\nid: 5adfe539190df80022801a50\nupdated: '2018-08-30T01:31:57.000Z'\ndate: 2018-05-04 21:11:00"]]
```

If you need a quick and dirty fix and don't need to support Markdown in your code blocks. Use the above fix and then make sure whenever you set `title` on a CodeBlock, you're actually passing in `[["your code here"]]` to [satisfy Notion.so's format](https://github.com/jamalex/notion-py/blob/master/notion/maps.py#L60-L66)

**Comment by jamalex** [comment] 2020-01-02 00:31
Good catch! It actually looks as if this isn't something specific to `CodeBlock`, as the same thing happens with a basic block when multiple lines prefixed with `-` are set. It's just less common outside of a CodeBlock. It seems to be a problem with the way I'm doing "Markdown to Notion" conversion. Or rather, I think it may just be an inherently tricky/ambiguous case, where it doesn't have a good way to tell, when going from Markdown to Notion format, when to interpret literally and when to interpret as Markdown annotations.

>the problem is the CodeBlock actually supports Markdown in it (?!)

Exactly. This would all be much easier if we could assume there's no styling within a code block. But as you've observed, in Notion you can select text within a code block and, for example, make it bold.

I'm thinking to add a parallel `title_plaintext` property that strips (and adds) the `[[ ]]`, but doesn't do any markdown conversion. I'll do a quick pass on that now, but let me know if you have any other suggestions.

**Comment by jamalex** [comment] 2020-01-02 00:42
After playing with this a bit more, a couple of observations:
1) The same problem happens with other types of Markdown in CodeBlocks (e.g. `__stuff_like_this__` for bolding). This doesn't cause issues in the same way for other block types because they automatically convert `__X__` and `*X*` on the fly into formatting as you type. This auto-styling doesn't happen in CodeBlocks.
2) I can't actually think of a case where dashes can be used for bullets within Notion (other than as a keyboard shortcut for converting the entire block into a `BulletedListBlock`). So there's no reason we should be touching dashes in the conversion process.

So... if it weren't for 1), then fixing 2) by ignoring dashes would be enough. I'm thinking to ignore dashes, but also just turn off markdown conversion completely for CodeBlock as suggested. This means that modifying an existing CodeBlock that had formatting internally will clear the formatting, but this seems like an uncommon scenario.

**Comment by Cobertos** [comment] 2020-01-02 00:43
I really like the idea of `title_plaintext`. It preserves the current API and gives the user the ability to choose which one to use. Kind of like `.innerHTML` and `.textContent` in a way...

**Comment by jamalex** [comment] 2020-01-02 00:45
Ok, cool, if that resonates, then I'll go with that, along with disabling dash-conversion in the standard markdown conversion.

**Comment by jamalex** [comment] 2020-01-02 02:02
Ok, done! Will be in the upcoming release: https://github.com/jamalex/notion-py/pull/84

**Closed by jamalex** 2020-01-02 02:02 UTC
